name: rtx

on:
  push:
    tags: ["v*"]
    branches: ["main", "release/*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  unit:
    runs-on: ubuntu-22.04
    container: ghcr.io/jdx/rtx:github-actions
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      # - uses: taiki-e/install-action@v2
      #   with:
      #     tool: nextest,just,cargo-deny,cargo-msrv,cargo-machete
      # - name: Install direnv/shfmt
      #   run: sudo apt-get update; sudo apt-get install direnv shfmt
      - name: Run cargo nextest
        run: cargo nextest run --all-features
        env:
          RUST_BACKTRACE: "1"
      - run: just lint
      - run: cargo deny check
      - run: cargo msrv verify
      - run: cargo machete --with-metadata

  coverage:
    name: coverage-${{matrix.tranche}}
    #container: ghcr.io/jdx/rtx:github-actions
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        tranche: [0, 1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: rustup toolchain install nightly --component llvm-tools-preview
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: coverage
          save-if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install zsh/fish/direnv
        run: sudo apt-get update; sudo apt-get install zsh fish direnv shfmt
      - run: npm i -g markdown-magic
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Run tests with coverage
        uses: nick-fields/retry@v2
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_BACKTRACE: "1"
          RTX_GITHUB_BOT_TOKEN: ${{ secrets.RTX_GITHUB_BOT_TOKEN }}
          TEST_TRANCHE: ${{matrix.tranche}}
          TEST_TRANCHE_COUNT: 4
        with:
          timeout_minutes: 30
          max_attempts: 2
          command: just test-coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: false
          files: lcov.info
